// This file was autogenerated by goog/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../app/app1.js', ['app1'], ['dashMVC']);
goog.addDependency('../../app/app2.js', ['app2'], ['dashMVC']);
goog.addDependency('../../base/Controller.js', ['dashMVC.Controller'], ['dashMVC.IObserver']);
goog.addDependency('../../base/IObserver.js', ['dashMVC.IObserver'], []);
goog.addDependency('../../base/ISubject.js', ['dashMVC.ISubject'], []);
goog.addDependency('../../base/Model.js', ['dashMVC.Model'], ['dashMVC.Subject']);
goog.addDependency('../../base/Subject.js', ['dashMVC.Subject'], ['dashMVC.ISubject', 'goog.array']);
goog.addDependency('../../base/View.js', ['dashMVC.View'], ['dashMVC.Subject']);
goog.addDependency('../../base/base.js', ['dashMVC'], ['dashMVC.Controller', 'dashMVC.Model', 'dashMVC.View']);
