// This file was autogenerated by goog/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../app/app1/app1.js', ['appCode'], ['app1.Bus', 'app1.BusController', 'app1.BusView']);
goog.addDependency('../../app/app1/application/Bootstrapper.js', ['app1'], ['dashMVC']);
goog.addDependency('../../app/app1/application/controllers/BusController.js', ['app1.BusController'], ['app1']);
goog.addDependency('../../app/app1/application/models/Bus.js', ['app1.Bus'], ['app1']);
goog.addDependency('../../app/app1/application/views/BusView.js', ['app1.BusView'], ['app1']);
goog.addDependency('../../app/app12.js', ['app12'], ['dashMVC']);
goog.addDependency('../../app/app22.js', ['app22'], ['dashMVC']);
goog.addDependency('../../base/Controller.js', ['dashMVC.Controller'], ['dashMVC.IObserver']);
goog.addDependency('../../base/IObserver.js', ['dashMVC.IObserver'], []);
goog.addDependency('../../base/ISubject.js', ['dashMVC.ISubject'], []);
goog.addDependency('../../base/Model.js', ['dashMVC.Model'], ['dashMVC.Subject']);
goog.addDependency('../../base/Subject.js', ['dashMVC.Subject'], ['dashMVC.ISubject', 'goog.array']);
goog.addDependency('../../base/View.js', ['dashMVC.View'], ['dashMVC.Subject']);
goog.addDependency('../../base/base.js', ['dashMVC'], ['dashMVC.Controller', 'dashMVC.Model', 'dashMVC.View', 'dashMVC.uri.router', 'goog.History']);
goog.addDependency('../../base/uri/Request.js', ['dashMVC.uri.Request'], ['goog.Uri']);
goog.addDependency('../../base/uri/router.js', ['dashMVC.uri.router'], ['dashMVC.uri.Request', 'goog.array', 'goog.object']);
